import type { Metadata } from "next";
import "./globals.css";
import { fontText } from "@/fonts/Fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontText.className}  `}>{children}</body>
    </html>
  );
}
