import type { Metadata } from "next";
import "./globals.css";
import { fontText } from "@/fonts/Fonts";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Wallet Watcher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`${fontText.className} bg-main  `}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
